export interface Movie {
  id: number
  title: string
  genres: string[]
  year: number
  globalRating: number
  image: string
}

export const MOVIES: Movie[] = [
  {
    id: 1,
    title: "Vingadores: Ultimato",
    genres: ["Ação", "Aventura"],
    year: 2019,
    globalRating: 4.8,
    image: "/avengers-endgame-inspired-poster.png",
  },
  {
    id: 2,
    title: "John Wick 4",
    genres: ["Ação", "Thriller"],
    year: 2023,
    globalRating: 4.6,
    image: "/john-wick-4-action-movie-poster.jpg",
  },
  {
    id: 3,
    title: "Mad Max: Estrada da Fúria",
    genres: ["Ação", "Aventura"],
    year: 2015,
    globalRating: 4.7,
    image: "/mad-max-fury-road-desert-action-poster.jpg",
  },
  {
    id: 4,
    title: "Top Gun: Maverick",
    genres: ["Ação", "Drama"],
    year: 2022,
    globalRating: 4.5,
    image: "/top-gun-maverick-fighter-jet-poster.jpg",
  },

  {
    id: 5,
    title: "Superbad",
    genres: ["Comédia"],
    year: 2007,
    globalRating: 4.2,
    image: "/superbad-comedy-movie-poster.jpg",
  },
  {
    id: 6,
    title: "Deadpool",
    genres: ["Comédia", "Ação"],
    year: 2016,
    globalRating: 4.4,
    image: "/deadpool-superhero-comedy-poster.jpg",
  },
  {
    id: 7,
    title: "Se Beber, Não Case!",
    genres: ["Comédia"],
    year: 2009,
    globalRating: 4.1,
    image: "/the-hangover-comedy-movie-poster.jpg",
  },
  {
    id: 8,
    title: "Borat",
    genres: ["Comédia"],
    year: 2006,
    globalRating: 3.9,
    image: "/borat-comedy-movie-poster.jpg",
  },

  {
    id: 9,
    title: "Parasita",
    genres: ["Drama", "Thriller"],
    year: 2019,
    globalRating: 4.9,
    image: "/parasite-korean-thriller-movie-poster.jpg",
  },
  {
    id: 10,
    title: "Coringa",
    genres: ["Drama", "Crime"],
    year: 2019,
    globalRating: 4.3,
    image: "/joker-dark-drama-movie-poster.jpg",
  },
  {
    id: 11,
    title: "Moonlight",
    genres: ["Drama"],
    year: 2016,
    globalRating: 4.4,
    image: "/moonlight-drama-movie-poster.jpg",
  },
  {
    id: 12,
    title: "Manchester à Beira-Mar",
    genres: ["Drama"],
    year: 2016,
    globalRating: 4.2,
    image: "/manchester-by-the-sea-drama-poster.jpg",
  },

  {
    id: 13,
    title: "La La Land",
    genres: ["Romance", "Musical"],
    year: 2016,
    globalRating: 4.3,
    image: "/la-la-land-musical-romance-poster.jpg",
  },
  {
    id: 14,
    title: "Nasce uma Estrela",
    genres: ["Romance", "Drama"],
    year: 2018,
    globalRating: 4.1,
    image: "/a-star-is-born-romance-drama-poster.jpg",
  },
  {
    id: 15,
    title: "O Notebook",
    genres: ["Romance", "Drama"],
    year: 2004,
    globalRating: 4.0,
    image: "/the-notebook-romance-movie-poster.jpg",
  },
  {
    id: 16,
    title: "Antes do Pôr do Sol",
    genres: ["Romance", "Drama"],
    year: 2004,
    globalRating: 4.2,
    image: "/before-sunset-romance-drama-poster.jpg",
  },

  {
    id: 17,
    title: "Duna",
    genres: ["Ficção Científica", "Aventura"],
    year: 2021,
    globalRating: 4.4,
    image: "/placeholder.svg?height=400&width=300",
  },
  {
    id: 18,
    title: "Blade Runner 2049",
    genres: ["Ficção Científica", "Thriller"],
    year: 2017,
    globalRating: 4.6,
    image: "/placeholder.svg?height=400&width=300",
  },
  {
    id: 19,
    title: "Interestelar",
    genres: ["Ficção Científica", "Drama"],
    year: 2014,
    globalRating: 4.7,
    image: "/placeholder.svg?height=400&width=300",
  },
  {
    id: 20,
    title: "Ex Machina",
    genres: ["Ficção Científica", "Thriller"],
    year: 2014,
    globalRating: 4.3,
    image: "/placeholder.svg?height=400&width=300",
  },

  {
    id: 21,
    title: "Corra!",
    genres: ["Terror", "Thriller"],
    year: 2017,
    globalRating: 4.2,
    image: "/placeholder.svg?height=400&width=300",
  },
  {
    id: 22,
    title: "Hereditário",
    genres: ["Terror"],
    year: 2018,
    globalRating: 4.0,
    image: "/placeholder.svg?height=400&width=300",
  },
  {
    id: 23,
    title: "Midsommar",
    genres: ["Terror", "Drama"],
    year: 2019,
    globalRating: 3.8,
    image: "/placeholder.svg?height=400&width=300",
  },
  {
    id: 24,
    title: "Um Lugar Silencioso",
    genres: ["Terror", "Thriller"],
    year: 2018,
    globalRating: 4.1,
    image: "/placeholder.svg?height=400&width=300",
  },

  {
    id: 25,
    title: "Homem-Aranha no Aranhaverso",
    genres: ["Animação", "Ação"],
    year: 2018,
    globalRating: 4.8,
    image: "/placeholder.svg?height=400&width=300",
  },
  {
    id: 26,
    title: "Coco",
    genres: ["Animação", "Família"],
    year: 2017,
    globalRating: 4.6,
    image: "/placeholder.svg?height=400&width=300",
  },
  {
    id: 27,
    title: "Soul",
    genres: ["Animação", "Drama"],
    year: 2020,
    globalRating: 4.4,
    image: "/placeholder.svg?height=400&width=300",
  },
  {
    id: 28,
    title: "Toy Story 4",
    genres: ["Animação", "Família"],
    year: 2019,
    globalRating: 4.3,
    image: "/placeholder.svg?height=400&width=300",
  },

  {
    id: 29,
    title: "Matrix",
    genres: ["Ficção Científica", "Ação"],
    year: 1999,
    globalRating: 4.8,
    image: "/placeholder.svg?height=400&width=300",
  },
  {
    id: 30,
    title: "Pulp Fiction",
    genres: ["Crime", "Drama"],
    year: 1994,
    globalRating: 4.9,
    image: "/placeholder.svg?height=400&width=300",
  },
  {
    id: 31,
    title: "O Poderoso Chefão",
    genres: ["Crime", "Drama"],
    year: 1972,
    globalRating: 4.9,
    image: "/placeholder.svg?height=400&width=300",
  },
  {
    id: 32,
    title: "Cidade de Deus",
    genres: ["Crime", "Drama"],
    year: 2002,
    globalRating: 4.7,
    image: "/placeholder.svg?height=400&width=300",
  },
  {
    id: 33,
    title: "O Senhor dos Anéis: A Sociedade do Anel",
    genres: ["Fantasia", "Aventura"],
    year: 2001,
    globalRating: 4.8,
    image: "/placeholder.svg?height=400&width=300",
  },
  {
    id: 34,
    title: "Harry Potter e a Pedra Filosofal",
    genres: ["Fantasia", "Família"],
    year: 2001,
    globalRating: 4.5,
    image: "/placeholder.svg?height=400&width=300",
  },
  {
    id: 35,
    title: "Forrest Gump",
    genres: ["Drama", "Romance"],
    year: 1994,
    globalRating: 4.6,
    image: "/placeholder.svg?height=400&width=300",
  },
]
